- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
    check:
      jobs:
        - monasca-tempest-python-mysql
        - monasca-tempest-python-postgresql:
            voting: false
        - monasca-tempest-java-mysql:
            voting: false
        - monasca-tempest-java-postgresql:
            voting: false
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - legacy-monasca-common-maven-build
    gate:
      queue: monasca
      jobs:
        - legacy-monasca-common-maven-build
    post:
      jobs:
        - legacy-monasca-common-localrepo-upload
