- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-train-jobs
    check:
      jobs:
        - monasca-tempest-python3-influxdb
        - monasca-tempest-python3-cassandra
        - monasca-tempest-java-cassandra
        - monascalog-tempest
        - build-monasca-common-docker-base-image
        - legacy-monasca-common-maven-build
    gate:
      queue: monasca
      jobs:
        - monasca-tempest-python3-influxdb
        - monasca-tempest-java-cassandra
        - monascalog-tempest
        - legacy-monasca-common-maven-build
    post:
      jobs:
        - publish-monasca-common-docker-base-image
        - legacy-monasca-common-localrepo-upload
    periodic:
      jobs:
        - publish-monasca-common-docker-base-image
    release:
      jobs:
        - publish-monasca-common-docker-base-image

- job:
    name: build-monasca-common-docker-base-image
    run: playbooks/docker_build_base.yml
    required-projects:
      - openstack/monasca-common
    attempts: 1
    irrelevant-files:
      - ^.*\.rst$
      - ^.*\.md$
      - ^doc/.*$

- job:
    name: build-monasca-docker-image
    run: playbooks/docker_build_service.yml
    required-projects:
      - openstack/monasca-common
    attempts: 1
    irrelevant-files:
      - ^.*\.rst$
      - ^.*\.md$
      - ^doc/.*$

- job:
    name: publish-monasca-common-docker-base-image
    parent: build-monasca-common-docker-base-image
    post-run: playbooks/publish.yml
    required-projects:
      - openstack/monasca-common
    vars:
      publisher: true
    secrets:
      - doker_hub_login

- secret:
    name: doker_hub_login
    data:
      user:  !encrypted/pkcs1-oaep
        - j009sQOrpIAhTBhYHjmjcZNuZlb+mIAHT4rMzo0qAsruGhTAsL1AgHvkm/FLLtK9mT6w3
          dAlHGC1Bba9n+H3INpkZbcNm0B2+PwIfjbB77lEcN/1D3XrXKje9S5IH3lWbBU+m4YIz0
          +EsqkgciFXiFytW9dTT2oT58vu7TlD9N983UqoJ89Z5jxoSdbquR22er2oX0txb1XNIrC
          M/7heQ/cigQtB9b04yEozhAUnZjFOPviCPv3R4aqbj5nmZ1w2UGc6HhZX0X0G4BRKlC+0
          T6wYWbPgYMsdNlTnJqcji3IArbQeT89dY5Dcp5XbpYHd9U3h6wdSfcRihmCVF5bSdfzMW
          E787kg0q81iFWPcCzbeQCsJexZ3osT7uoow/j4ddshbbQxM6aLRmK56prCXNTxFebSQJh
          oqux2V7G+U9KCDya7dWe7Id3oMV0hxLIZI615evEtrzjjnsCVFRiOEn5AZdyfKe6uFxeD
          fjTlM3y9gNpYV2wEcxm2+q8H9xCwlwA1IwZ+rTjCN1NJ53ded+Vs7CUpvkOlFEYMAUD4f
          aHCyT9mPBDzVBw7TSqJTM6wn+LKkiV87b8QDFcYFZZT4aoIWNLU2dyS5Dk/qc0c3WUNxO
          vQybCmnG2qIVh+Y4k/FNnPi0BvIyf9d78CEg5ZSTlG517zeqmohKybW3ynlYBM=
      password: !encrypted/pkcs1-oaep
        - Bvz5Lf62vqtUfneRd9IcZ+HcR3PG5r0xNk1aWRNVlJ+T4NSoLE9wQe3HLLkKIBG9pYIJN
          60x+2EziPVYFrwMJloqOiuKHZmifjbYeNTK/FOlMHXxcQACYMc67ZDZO5VtIWtiCzM0aR
          iN8f5n/kfVa0rPeHnKbabUd4XuTZv0PltT+GyYsLAcM+QqQcfWuYhx4ahiFMF+bpLMUEj
          kJIFSKu7sk+6XHR6P5ppiUNl/yZzDztezkWS6HGGVaP0nV7nNaOd2hFIwl64iS4er1M6I
          mc3XdOF1xJyU7IFrVsBlP8LYFS69wlSq3EuUoPYkR/7nk9cTKqmvXo/lThR7Yv9ZTbHxq
          5pMAmURMQCVwZYDTDv6E1uQMhrGZliVjEsDmIpBG0Om61IpvEWIHm0WiS7OMG/e98IUOD
          fhyjDMo9IzlsuilWH8xSwfh8f+UHaAwOF60bXEs9b2Zowwzvbi++AwtGbhoaidzaA1e6t
          27YDErM/Ll8uawY+sLxO2JpE0AQM93lXVQmMg5npN0dlgIkCSohxCRlkiRrZ1DWx80ZiC
          3nzYnRYQav/cRLp8mhVTLoLrBI5edu8uRw8kfMQWAbFpxvaCVwiii78izJsmJPmPelczS
          YNZV98I1+pV7KW0PUS5EArkBCWDHLSZT4v4E8m4RfcXMlK7nWUQdN49sWDZg8A=
