---
- hosts: all
  tasks:
    - name: Run node setup script
      shell: "{{ zuul.project.src_dir }}/playbooks/setup_ci.sh"
      become: true

    - name: Changing permission of Docker socket to 666
      file:
        path: /run/docker.sock
        mode: 666
      become: true

    - name: Build monasca-base Docker image
      shell: "{{ zuul.project.src_dir }}/docker/build_base_image.sh"
      environment:
        MONASCA_COMMON_TAG: "{{ zuul.tag if zuul.pipeline == 'release' else zuul.branch | basename }}"
      become: true

    - name: List images
      shell: "docker images  --format '{% raw %}{{ .Repository }}:{{ .Tag }}{% endraw %}' | grep monasca"
